[package]
name = "cmd-hero"
version = "0.1.0"
authors = ["Magnus Jacobsen <magnusjacobsen@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
